### ISSUE TITLE
Get app

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [hugbug/conpianist#25]
Hi,

Just ordered a CSP-170. Looking at options to connect it to a desktop PC and/or Mac and came across this project. 
Did you get a chance to get on with software development?
How can we get hold of the app?
I'll be happy to help development with my very limited skills...

**Comment by hugbug** [comment]
That projects exists for 1,5 years but you are the first one asking about it ;) That shows how insignificant it is to the community. That also explains why I've lost interest in developing it and have no plans on spending further hundreds of hours on it.

Nonetheless the program can:
- connect to piano via network (but can't connect via USB cable);
- upload midi-files to piano;
- playback control of uploaded midi-files (start, pause, position);
- stream lights control (on, off);
- guide mode control (on, off);
- playback selected fragment;
- volume, tempo, transpose;
- select voices (all seven hundreds) for main, left and layer;
- show scores with correct playback position - scores must be loaded from a separate muscixml-file (can't show scores directly from midi-file).

![Playback with scores](https://user-images.githubusercontent.com/3368402/64079783-1b11a480-ccec-11e9-9511-b94286b3855a.png)

![Voice selection](https://user-images.githubusercontent.com/3368402/64079788-206eef00-ccec-11e9-9fe7-bc7ece795525.png)

At current stage it is a no replacement for official app. Still if you want to try it I can provide you with a compiled version for macOS - please send me a note to nzbget@gmail.com.

**Comment by djangobaer** [comment]
Hi!
I'm from austria and brandnew in this forum. I play CSP-170 since 2 years and work with a lot of midi and Sysex-commands. The App Smart Pianist makes me not very happy and the Yamaha-Support is stupid. So I am very interested to work on this matter with you.
Best regards

Harald

**Comment by hugbug** [comment]
@djangobaer 
I can send you compiled app for macOS if you give me your email-address. Send me a note to nzbget@gmail.com so that I know it.
I do not have compiled binaries for Windows or Linux.

I'm not active on this project for a long time. I'm not a musician but just a programmer who was interested in reverse engineering of CSP-170 communication protocol. It was quite a success and I've implemented many features of the smartphone app. At some point I've lost interest eventually.

**Comment by hugbug** [comment]
I've published the first version. Please see [releases section](https://github.com/hugbug/conpianist/releases).
