### ISSUE TITLE
Balance control

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#33]
We need **Balance dialog** to change relative volumes of sound sources: main, left, layer, MIDI-song, Mic and Aux In.

Screenshot from Smart Pianist:
![Foto 14 03 20, 18 48 25](https://user-images.githubusercontent.com/3368402/76687489-c351df80-6624-11ea-9ff3-1e63717b2e1f.png)

We don't need volume slider for Style. The Styles are not supported in ConPianist at all yet.

**Comment by djangobaer** [comment]
Ok, the styles would be nice if they work with score and falling lights. But does not!
Otherwise I think also there is no need for them.
