### ISSUE TITLE
Voice settings (octave, pan, reverb)

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#35]
We want to be able to select octave shift, pan and reverb level per Main, Left and Layer. Also to select reverb effect (for all three voices).

Screenshots from Smart Pianist:
![Foto 14 03 20, 18 17 36](https://user-images.githubusercontent.com/3368402/76688436-0b750000-662d-11ea-9ce1-3c3bac65ca30.png)

![Foto 14 03 20, 18 17 47](https://user-images.githubusercontent.com/3368402/76688440-1465d180-662d-11ea-9ffc-3a5cbd55cee0.png)

Pan and reverb setting can be put in the same dialog with octave shift. The voice volume sliders duplicate the function from **balance dialog** and are not strictly necessary here.

In this issue:
- [x] create UI (a new dialog or integrate into existing dialogs);
- [x] determine octave state;
- [x] change octave state;
- [x] determine pan state;
- [x] change pan;
- [x] determine reverb state;
- [x] change reverb value;
- [x] determine reverb effect;
- [x] change reverb effect.

**Comment by djangobaer** [comment]
Idea!
In that window (both in one) it is possible to integrate the balance needs.
![image](https://user-images.githubusercontent.com/62076869/76704473-93b0df00-66d9-11ea-8713-ee1f20caa35c.png)

**Comment by hugbug** [comment]
Pan, Reverb and Reverb Effect are no integrated into **Balance Dialog**.
![Screen Shot 2020-03-27 at 17 23 20](https://user-images.githubusercontent.com/3368402/77778081-c56a6400-7050-11ea-92c0-99c844d4796b.png)
For **Octave** another place is needed. I've tried putting it into the Balance dialog but it didn't look well. I'll see if I can put them into Voice selection pane.

**Comment by hugbug** [comment]
Changing of octave shift is implemented via a context menu for each voice:

![Screen Shot 2020-03-29 at 20 01 43](https://user-images.githubusercontent.com/3368402/77856631-be7e5580-71f8-11ea-85ab-2c332e95951c.png)
