### ISSUE TITLE
MIDI-Song mixer (channels on/off, volume, pan and reverb)

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#36]
We need a song mixer where we can change playback settings for MIDI-channels of the loaded MIDI-file. This includes mute/unmute channel, change volume, pan and reverb level.
In addition the reverb effect can be changed globally for all channels.

Screenshot from Smart Pianist:
![Foto 14 03 20, 18 21 59](https://user-images.githubusercontent.com/3368402/76688575-5b07fb80-662e-11ea-8cf7-9f19ed54ebad.png)

Smart Pianist detects channels present in the MIDI-file and disables controls for non-existing channels. It also shows nice icons for instruments. That requires a collection of icons. We could at least show instrument names or category (such as "piano", "drums"). For that we need to detect instruments in the MIDI-file too.

In this issue:
- [x] basic pane for Mixer;
- [x] UI controls for channel on/off, pan, reverb, volume;
- [x] determine volume state per channel;
- [x] determine pan state per channel;
- [x] determine reverb state per channel;
- [x] change volume per channel;
- [x] change pan per channel;
- [x] change reverb per channel;
- [x] determine channel on/off state;
- [x] change channel on/off;
- [x] create common UI component for channel and use it in Mixer and Balance;
- [x] detect voices for channels;
- [x] detect reverb effect;
- [x] change reverb effect;
- [x] detect non-used channels when loading a song;
- [x] deactivate non-used channels in mixer and disable them completely (prevent activation).

**Comment by djangobaer** [comment]
Yes!
I try to build instrumenticons in a file to select. Give you a info soon.

**Comment by hugbug** [comment]
## Screenshots

**Mixer**
![Screen Shot 2020-03-27 at 17 22 21](https://user-images.githubusercontent.com/3368402/77777231-91427380-704f-11ea-9b89-9ec66e0e2b72.png)

**Updated Balance Dialog**
![Screen Shot 2020-03-27 at 17 23 20](https://user-images.githubusercontent.com/3368402/77777312-afa86f00-704f-11ea-9fb5-d785fb3462d4.png)

**Comment by hugbug** [comment]
## Screenshots

![Screen Shot 2020-04-15 at 17 13 30](https://user-images.githubusercontent.com/3368402/79354913-4ffdff00-7f3d-11ea-8bf9-0ecda2180204.png)

![Screen Shot 2020-04-15 at 17 20 08](https://user-images.githubusercontent.com/3368402/79354993-6906b000-7f3d-11ea-9f09-7374209e0bea.png)
