### ISSUE TITLE
Song playback settings (stream lights speed, guide type)

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#37]
Stream lights can be already switched on/off directly in the main window. We also need a way to change stream lights speed and guide type.

Screenshots from Smart Pianist
![Foto 14 03 20, 18 20 27](https://user-images.githubusercontent.com/3368402/76688746-dd44ef80-662f-11ea-8823-bd5b2bb69a45.png)

![Foto 14 03 20, 18 20 50](https://user-images.githubusercontent.com/3368402/76688747-e5049400-662f-11ea-8556-728e2eb19b11.png)

Note: for selecting of MIDI part channel there is a separate issue.

**Comment by djangobaer** [comment]
Idea!
That should be in a general Settings-Window together with other basic settings.
The mixer should be in the songsection.

**Comment by hugbug** [comment]
Added context menus which opens via right mouse button on stream lights button or guide button. From the menus the stream lights speed and guide type can be changed. On touchscreen (iOS) a long tap opens context menu.

That's not perfect solution because not intuitive but that's OK for now.
