### ISSUE TITLE
MIDI part channel selection

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#38]
Currently the MIDI part channels are selected by the piano automatically. That doesn't work well for complex MIDI-files. We need a way to select channels manually.

Screenshots from Smart Pianist
![Foto 14 03 20, 18 20 27](https://user-images.githubusercontent.com/3368402/76688783-7ecc4100-6630-11ea-94f9-1b2b58c9fac1.png)

![Foto 14 03 20, 18 21 02](https://user-images.githubusercontent.com/3368402/76688789-8986d600-6630-11ea-87d9-0b3876598728.png)

That's one of the areas where we should improve over Smart Pianist solution. In Smart Pianist it's very inconvenient. To change the channel the song must be paused first, then you go into the settings and select the channels from sub-dialogs. But before you do that you need to know which channels to choose. For that you goes to song-mixer to see the instruments. Here you need to remember the channel numbers. 

It would be much better to select MIDI parts in the song-mixer instead.

**Comment by djangobaer** [comment]
Idea!
In Mixer-view you can switch on/off each channel, you can edit Pan, reverb and the voice.
When you build buttons on each channel, where you can chose two of them the problem was saved in one window.
Harald

**Comment by hugbug** [comment]
Yes, that's what I meant too ;)

**Comment by hugbug** [comment]
Integrated MIDI channel selection into the mixer. Channels which are selected for left/right hand parts have labels **R** or **L**:
![Screen Shot 2020-04-04 at 14 57 18](https://user-images.githubusercontent.com/3368402/78451341-65de0b00-7685-11ea-8d2b-0a7e5816bc11.png)

Each channel has a context menu where the part can be selected:

![Screen Shot 2020-04-04 at 14 57 40](https://user-images.githubusercontent.com/3368402/78451347-7098a000-7685-11ea-8820-9dcbe9c3678a.png)

Channel selection via mixer is much more comfortable than in Smart Pianist.

Another enhancement comparing to Smart Pianist. Piano has a limitation that the part cannot be changed during playback. Smart Pianist shows an explaining message and doesn't allow change. We made it better. The channel can be changed even during playback. In such case we pause playback, change channel, restore playback position (which piano resets when changing channels for parts) and resume playback.

In the future selected midi-channels can be saved into registration memory (#39).
