### ISSUE TITLE
Registration memory

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#39]
The registration memory is a very convenient feature in Smart Pianist. With it all settings can be saved into a file. Then later the settings can be loaded. This allows to quickly recall settings required for a particular MIDI-file. In fact the selected MIDI-file is part of the settings and the MIDI-file is loaded with all associated settings with just few clicks.

Screenshots from Smart Pianist
![Foto 14 03 20, 18 15 33](https://user-images.githubusercontent.com/3368402/76689007-60674500-6632-11ea-80e8-70fadae8ccd8.png)

![Foto 14 03 20, 18 16 30](https://user-images.githubusercontent.com/3368402/76689018-75dc6f00-6632-11ea-8ad8-6c88aa93c53d.png)

**Comment by djangobaer** [comment]
I work with registration mem only for Voice-Arrangements and all is working well. But to use it for complete songs, there is an export-option missing. So you can not edit anything inside the song.
If we build that exporttool may be its a good idea.

To you know what "Other" means or include?

Harald

**Comment by djangobaer** [comment]
I changed over to store my midi-files in RegMem by loading the file from Userfiles, searching the wright Voices in RegMem and store the song with "voices", "song", "style" and "others" activ. 
So all settings are ok and i can load the song and play. 
In a next step I canceled the Song in Userfiles. After that I tried to start the song from RegMem.
Nothing happens. So the conclusio is, RegMem has only a link to the song in Userfile stored and not the full song. So you need both, User-Songs and RegMem?!?!?! It is a nogo!

**Comment by hugbug** [comment]
Yes, you need both, the song and the regmem. What's the problem and why a nogo?

**Comment by djangobaer** [comment]
It is complicated in that way. To have an overview you have to bind that both memories via naming or else. I did it with a number in the RegMem and added those number to the filename in User-Songs. But I have only 150 songs and became troubles to hold it together.
Why they need 2 things for one reason. To store all infos from the song. I think it is easy to to that. using one file only.

**Comment by hugbug** [comment]
>It is complicated in that way.

What is more completed:
1) load midi-file into SmartPianist, then set all parameters in UI to you likings (voice, volume, everything else). Then store that as a preset. Anytime later if you want to play that song you open regmem list and choose the regmem for that song (if you name it properly it's easy to find). Now you can play the song (it's loaded automatically) with all the settings as you configured previously.

2) use a midi-editor to load the midi-file, then manually add a lot of sysex-commands to configure the playback parameters for that song. Then upload the song to SmartPianist. Yes, you have only one file. But that's the only advantage. If you want to make a small modification (change voice volume for example) you need to go back to your midi-editor.

Now you call Variant 1 "complicated"? Maybe it's complicated but Variant 2 is a nightmare.

**Comment by djangobaer** [comment]
Yes I agree, both ways are a lot of work. I gave up for today, because I changed 10 Files in your 1. way. 
After changing and storing, I tried it again. One of them is working ok, the others have sounds I never implemented. I think if you change something on Songname, or/and RegMem it doesnt work correct.

Never mind. I will wait till ConPianist is ready. You are near by to reach that target. I see ConPianist today is better and more interesting as Smarty. 

The 2nd way is realy a nightmare, but you have to work through midifiles from internet to can play it on CSP. When you find a way to store the changings you do in ConPianist, anywhere it will be a good solution.

**Comment by hugbug** [comment]
## Registration memory feature has been implemented

- The whole piano/program state can be saved into a file - registration memory file with file extension `.conmem`.
- Registration memory files can be loaded any time later.
- There are two menu commands in main menu: "Save Piano State" and "Load Piano State".
- In addition to manual loading via menu there is an automatic. When a midi-file is loaded the program checks if there is registration memory file for that midi-file (same file name as midi but with extension .conmem). If the file exists it's loaded automatically.

## How to use automatic registration memory
1. Open a midi-file.
2. Change song/program settings as you need.
3. Via main menu use command "Save Piano State". A save file dialog appears with suggested file name equal to song name. Just keep the suggested name and hit save button.
4. Now your midi-file has an associated registration memory file which will be loaded automatically next time you load the midi-file.
5. If you need to readjust some settings, just do that in program and then save piano state again under the same file name (overwrite existing file).

## Notes
- The name of the midi-file isn't saved into registration memory file. The automatic loading is based purely on file name equivalence. If you rename the midi, you should also rename the conmen-file.
- Conmen-file is an xml-file, which can be viewed or edited in any text editor.
- When the registration memory file is loaded, only the settings contained in the file are changed. Therefore using a text editor you can remove anything from the file and use such file to load certain settings. In such case you'll probably save the registration memory file as a separate thing not associated with any midi-file.
- For example you can configure voices (main, layer, left, octaves, split point), then save the piano state. The registration memory file will contain all piano and program settings but you can open it in a text editor and remove everything except of voices-section. Then you can load this file any time later to quickly select voices. All other settings will be preserved.
- I'm thinking about implementing an options dialog which will popup when using command "Save Piano State". In the dialog the user can select which settings to save into file. That should make the manual editing unnecessary.

**Comment by djangobaer** [comment]
Perfect!!!! What an application!!!
