### ISSUE TITLE
Show only selected parts in score view

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#42]
Currently the score view shows the whole content of MusicXml-file. In most cases the user wants to see only the parts he or she plays.

In this issue:
- [x] investigate if it's possible in Lomse to show only selected instruments from the score file;
- [x] detect which channels the piano selects (automatically) when a song is loaded;
- [x] update score view.

Later when the selecting of channels to play is implemented (#38), this should of course have an effect on score view as well.

Implementing this should also solve #41 .

**Comment by djangobaer** [comment]
I found that PlugIn for muse score 3.
This Plugin for MuseScore will go through a specified folder and can convert all formats MuseScore can read into all formats MuseScore can write, and only does so when no up-to-date version of the target format already exists.

May be helpful! I will test it.

**Comment by djangobaer** [comment]
Sorry I forgot the link:
https://musescore.org/en/project/batch-convert
