### ISSUE TITLE
Pics for Instruments

### ISSUE THREAD

**Issue by djangobaer** [hugbug/conpianist#44]
We wil need pics in 128x128px and larger for instruments on Channels.
Look at examples. If you agree I work on that.
#
Harald

![ElectricPiano128x128](https://user-images.githubusercontent.com/62076869/76967767-221aa000-6928-11ea-9ad1-771765692192.png)
![ElectroPiano800x600](https://user-images.githubusercontent.com/62076869/76967770-234bcd00-6928-11ea-8ad7-e116dc5404ed.png)
<img width="64" alt="GrandPiano128x128" src="https://user-images.githubusercontent.com/62076869/76967772-23e46380-6928-11ea-9444-f900befc0989.png">
<img width="400" alt="GrandPiano800x600" src="https://user-images.githubusercontent.com/62076869/76967775-23e46380-6928-11ea-9eee-cfa67afac920.png">
<img width="64" alt="UprightPiano128x128" src="https://user-images.githubusercontent.com/62076869/76967778-247cfa00-6928-11ea-8c4a-beeabca37165.png">
![UprightPiano800x600](https://user-images.githubusercontent.com/62076869/76967780-247cfa00-6928-11ea-82ca-e0fc1022056b.png)

**Comment by hugbug** [comment]
The icons are fine but where they come from? We can use art work with open source license only.

**Comment by djangobaer** [comment]
I did the pics per screenshot on iPad from Smart Pianist. Ok I use artwork instead and build small 128x128 px for channelview named by the Groups. For larger pics is no need, till we search via treeview. I can use the number plus alpha you named the instruments for that listing in presets code.
