### ISSUE TITLE
Scrollbar, scroll wheel, touchpad and touchscreen behaviour

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#55]
Mixer contains many UI controls that do not fit into one window; therefore the mixer is scrollable. Trying to use scroll wheel, touchpad and touchscreen in the mixer causes many collisions between slider/button-controls and underlying scrollview.

Attempts to change value of a slider using scroll wheel or touchpad causes the scrolling of the window content at the same time. That needs to be improved. The scroll wheel and touchpad should work either for sliders or for scrollview but not for both.

Controlling on touchscreen (iOS) is challenging too. The scrollview starts scrolling when trying to change slider values. That's not standard iOS behaviour, but JUCE (UI library) doesn't care. We should find ways to improve this.

- [x] improve scroll wheel and touchpad behaviour (Mac, Windows);
- [x] improve touchscreen behaviour (iOS).

**Comment by djangobaer** [comment]
An easy way is spliting the 16 channels in 2 x 8 channel in two different tabs (1-8, 9-16)

Also it can be helpful to highlight the backcolor of selected items by flyover such as selected instruments in tab voices.

**Comment by hugbug** [comment]
Splitting into tabs is bad because the window width is different for all users and there is also a zoom setting in the program.

I've implemented this:
1. scroll wheel and swipe gestures on touchpad scroll the underlying view and do not change sliders;
2.  on touchscreen (iOS) the touch gestures on sliders change slider values; scrolling of the view is possible with swipe gesture on buttons or empty areas.
