### ISSUE TITLE
Exception in Lomse with certain MusicXML-files when hiding instruments

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#66]
We have some MusicXML-files that causes crashes. That needs to be investigated.

**Comment by hugbug** [comment]
After more testing I can tell that these are not crashes. Instead Lomse throws a `runtime_error` - the callstack on the left:

![Screen Shot 2020-04-22 at 23 33 59](https://user-images.githubusercontent.com/3368402/80036372-e4de9a80-84f1-11ea-8e45-820a2bf668e7.png)

All works good without exception if all instruments are displayed. The problem occurs only when displaying limited number of instruments.

To show only selected instruments I do manipulate the instruments collection after the score is loaded - as explained here in https://github.com/lenmus/lomse/issues/208#issuecomment-614236169.

The error can be reproduced with the following score file (when removed all instruments except first two): [Russel-A Song For You-A.musicxml.zip](https://github.com/hugbug/conpianist/files/4519160/Russel-A.Song.For.You-A.musicxml.zip)

I guess my technique to hide instruments isn't perfect.

**Comment by hugbug** [comment]
The error is now catched and printed in the score view. No program crash anymore:

![Screen Shot 2020-04-24 at 18 15 05](https://user-images.githubusercontent.com/3368402/80235570-2722eb80-865a-11ea-92da-be65f15ecbfc.png)

Still don't know why the issue happens and if it can be fixed.

@cecilios: may be you have a tip?

**Comment by cecilios** [comment]
No, sorry. I have to look at the code you use for hiding/reordering instruments. The most probably cause for this error is some collateral issue of your code. I don't remember the details but If the score has groups of instruments (instruments grouped by bracktes) probably it is necessary to also reorganize the groups (ImoInstrGroups).

I will code an API method for this, as suggested in https://github.com/lenmus/lomse/issues/208#issuecomment-614236169 but I'm currently working on another issue. The new API method deserves adequate attention. I will look at it ASAP.

**Comment by hugbug** [comment]
You were right. The issue is with groups not adjusted after removing instruments.

I was able to reduce the example MusicXML-file to a bare minimum - two instruments and a couple of notes. Example file - [1Russel-A Song For You-A3.musicxml.zip](https://github.com/hugbug/conpianist/files/4531892/1Russel-A.Song.For.You-A3.musicxml.zip)

To reproduce the issue all you need is to remove the first instrument after the document is loaded:
```C++
score->get_instruments()->remove_child(score->get_instrument(0));
score->end_of_changes();
```

The problem goes away when the group is also removed:
```C++
score->get_instruments()->remove_child(score->get_instrument(0));
score->get_instrument_groups()->remove_child(score->get_instrument_groups()->get_child(0));
score->end_of_changes();
```

**Comment by hugbug** [comment]
I added code to hide/show groups in sync with hidden/shown instruments. That fixed the error with files which failed before.

That's OK for now. I'll migrate to the new API when it becomes available.
