### ISSUE TITLE
Message delivery with confirmation

### ISSUE THREAD

**Issue by hugbug** [hugbug/conpianist#71]
ConPianist communicates with the piano via MIDI-messages. Sometimes we need to send many MIDI-messages to piano at once. For example after connecting to the piano we want to know current piano state. For each piano property we send a request-message and piano sends a response-message back.

Currently more than 170 messages are sent when syncing piano state. That number will only increase in the future as we enhance the program.

The piano can process messages at a limited speed. If we send too many messages in a short interval the piano may skip some of them and we don't get the responses. To avoid this currently we do small pauses between groups of messages. The lengths of pauses were determined empirically. That's unfortunately not 100% reliable. We could increase the pauses but then it would take unnecessary too long to exchange all the needed messages.

Smart Pianist makes that differently. It sends one message, then it waits for the response. Then it sends the next message.

**We need a similar system in our program.**

Advantages:
- all messages are delivered and processed by the piano;
- possible enhancement: we can even do an automatic resend of the message if no response is received within specified timeframe.

Potential disadvantages:
- sequential sending of messages may take longer than sending them in batch like we do now.

A possible enhancement for the potential slowness would be to send multiple messages in a batch and then wait for confirmations for all of them. That's however would be a separate tracker-issue. We need to implement the first stage first.

**Comment by djangobaer** [comment]
I remember by sending midi messages to CSP, that there are often a lot of answer-lines received back from CSP. Make sence to check how much time they really take. I think our problem with the split is around here. Great work.
