### ISSUE TITLE
 ‘BinaryData’ has not been declared

### ISSUE THREAD

**Issue by ayyb1988** [hugbug/conpianist#84]
conpianist/Source/Mixer/ChannelComponent.cpp:45:59: error: ‘BinaryData’ has not been declared
   45 |                                ImageCache::getFromMemory (BinaryData::buttonkeyboardwide_png, BinaryData::buttonkeyboardwide_pngSize), 1.000f, Colour (0x00000000),

where can i find it

**Comment by hugbug** [comment]
It is generated by ProJucer. May be it works differently in newer versions, I was using 5.4.7.

**Comment by ayyb1988** [comment]
Thanks
