### ISSUE TITLE
Using JUCE to show the lomse-rendered score, but it didn't render successfully

### ISSUE THREAD

**Issue by ayyb1988** [hugbug/conpianist#85]
![Screenshot from 2022-03-30 17-29-59](https://user-images.githubusercontent.com/7148115/160799666-d1fe9885-0cca-48a2-8b13-8ed640ab9c0d.png)

**Comment by ayyb1988** [comment]
mid and xml is using :
Game of Thrones (piano).mid
Game of Thrones (piano).musicxml

**Comment by cecilios** [comment]
What is this? What is the Lomse issue?

**Comment by hugbug** [comment]
The status message "looking for the instrument" suggests there is no connection to piano. The button "Click here and select a song" does not work until a connection is established.

**Comment by ayyb1988** [comment]
solved this problem：

in method of `LomseScoreComponent::PrepareImage()`

add        ` interactor->set_rendering_buffer(bitmap.data,getWidth(),getHeight());`  before   ` interactor->redraw_bitmap();`   

losme0.29 and juce6.16
